const Map<String, String> appStringsEn = {
  'appName': 'SudokuNote',
  'appTagline': 'Sudoku with notes',
  'chooseDifficulty': 'Choose difficulty',
  'chooseDifficultyHint': 'Each puzzle is a small logic challenge.',
  'diffEasy': 'Easy',
  'diffEasyHint': 'A good place to start',
  'diffMedium': 'Medium',
  'diffMediumHint': 'Balanced and fun',
  'diffHard': 'Hard',
  'diffHardHint': 'A real thinking test',
  'diffExpert': 'Expert',
  'diffExpertHint': 'For people who like a challenge',
  'continueGame': 'Continue saved game',
  'playTitle': 'Sudoku',
  'undo': 'Undo',
  'erase': 'Erase',
  'notes': 'Notes',
  'doneTitle': 'Complete!',
  'doneBody': 'You solved this Sudoku.',
  'statDifficulty': 'Difficulty',
  'statFilled': 'Cells filled',
  'statNotes': 'Notes placed',
  'statResult': 'Result',
  'resultGreat': 'Great!',
  'nextGame': 'Next puzzle',
  'otherDifficulty': 'Choose another difficulty',
  'savedGame': 'Game saved',
  'heroTitle': 'Practice typing.\nGet faster.',
  'testDuration': 'Test duration',
  'seconds30': '30 seconds',
  'seconds60': '60 seconds',
  'language': 'Language',
  'englishUs': 'English (US)',
  'vietnamese': 'Vietnamese',
  'start': 'Start',
  'typingTest': 'Typing Test',
  'remaining': 'remaining',
  'typed': 'typed',
  'mistake': 'mistake',
  'mistakes': 'mistakes',
  'accuracy': 'accuracy',
  'testResults': 'Test Results',
  'wellDone': 'Well done!',
  'wpm': 'WPM',
  'typedCharacters': 'Typed characters',
  'correctCharacters': 'Correct characters',
  'incorrectCharacters': 'Incorrect characters',
  'time': 'Time',
  'retry': 'Retry',
  'chooseNewTest': 'Choose New Test',
  'practiceMistakes': 'Practice Mistakes',
  'focusImprove': 'Focus\nand improve.',
  'typeEachWord': 'Type each word correctly.',
  'nextSet': 'Next Set',
  'myProgress': 'My Progress',
  'progress': 'Progress',
  'savedTests': 'Saved Tests',
  'averageSpeed': 'Average Speed',
  'averageAccuracy': 'Average Accuracy',
  'savedPracticeTexts': 'Saved Practice Texts',
  'add': 'Add',
  'practice': 'Practice',
  'results': 'Results',
  'texts': 'Texts',
  'profile': 'Profile',
  'noResults': 'Finish a test to see your speed and accuracy.',
  'noTexts': 'Save a paragraph you actually type — messages, notes, or study lines.',
  'textTitle': 'Title',
  'textBody': 'Passage',
  'saveText': 'Save passage',
  'needProTexts': 'Unlock SudokuNote Pro to keep more than {n} passages.',
  'wpmGoal': 'Speed goal',
  'goalHint': 'Aim for a WPM target. Unlock Goals in Shop to edit it.',
  'commonMisses': 'Words you miss',
  'secondsN': '{n} seconds',
  'shop': 'Shop',
  'shopMarket': 'SudokuNote Shop',
  'shopMenuThemes': 'Themes',
  'shopMenuBackgrounds': 'Looks',
  'shopMenuSkins': 'Cells',
  'shopLooksNote': 'Looks only. Themes, backgrounds, and cell styles dress the board. They do not change the puzzle or the rules.',
  'shopMenuFeatures': 'Tools',
  'shopFuel': 'Earn or buy coins',
  'shopRefuel': 'Buy coins',
  'claimDaily': 'Daily',
  'dailyClaimed': 'Done',
  'dailyRewardClaimed': '+{amount} daily coins',
  'spinNow': 'Lucky',
  'spinRewardEarned': '+{amount} lucky coins',
  'apply': 'Apply',
  'inUse': 'In use',
  'useDefault': 'Default',
  'featureOn': 'On',
  'featureOff': 'Off',
  'applied': 'Applied',
  'purchaseSuccess': 'Unlocked',
  'insufficientCoins': 'Need more coins',
  'alreadyOwned': 'Already owned',
  'purchaseFailed': 'Purchase failed',
  'openingBilling': 'Opening Google Play…',
  'restorePurchases': 'Restore purchases',
  'restoreStarted': 'Checking Play purchases…',
  'removeAdsUnlocked': 'Ads removed',
  'proUnlocked': 'Pro unlocked',
  'coinsAdded': '+{amount} coins',
  'coinsAddedWithBonus': '+{amount} coins with bonus',
  'activityCreateReward': '+{amount} for starting a puzzle',
  'activityMilestoneReward': '+{amount} for a clean solve',
  'activityCardReward': '+{amount} for finishing a puzzle',
  'coinEarned': '+{amount} coins',
  'coinRewardSub': 'Balance: {balance}',
  'configTimeout': 'Shop config timed out. Coin packs may be hidden.',
  'configNetworkError': 'Shop config unavailable. You can still spend coins.',
  'defaultRestored': 'Back to the default look',
  'buyCoins': 'Buy coins',
  'buyCoinsDesc': 'Buy again whenever you need more coins. Playing also earns coins.',
  'hotDeal': 'Weekly deal',
  'bestValue': 'Best value',
  'firstBonus': 'First-buy bonus',
  'hotDealBadge': 'HOT',
  'bestValueBadge': 'BEST',
  'firstPurchaseBadge': '+50% first buy',
  'coinBalanceLabel': 'Your coins',
  'coinPack': 'Coin pack {num}',
  'coinBonusExtra': '{base} + {bonus} bonus',
  'purchasePromoDesc': 'Pack {pack} this week: {coins} coins (+{bonus})',
  'billingUnavailable': 'Google Play Billing is not available on this device.',
  'productsNotFound': 'No coin packs found. Create sn_pack_1–10 in Play Console.',
  'earnCoinsHint': 'Solve a puzzle, claim the daily, or spin lucky — then buy coins if you still need them.',

  'shopThemeDefault': 'Navy',
  'shopThemeDefaultDesc': 'The SudokuNote look. Navy type on a pale blue page.',
  'shopThemeMint': 'Mint',
  'shopThemeMintDesc': 'Cool green accent around the board.',
  'shopThemeDusk': 'Dusk',
  'shopThemeDuskDesc': 'Violet evening palette.',
  'shopThemePeach': 'Peach',
  'shopThemePeachDesc': 'Warm paper and a soft accent.',
  'shopThemeIce': 'Ice',
  'shopThemeIceDesc': 'Crisp cyan highlights.',
  'shopThemeNight': 'Night',
  'shopThemeNightDesc': 'Dark page with a light board.',
  'shopBgDefault': 'Plain',
  'shopBgDefaultDesc': 'Quiet pale background behind the board.',
  'shopBgGrid': 'Notebook',
  'shopBgGridDesc': 'Faint lines behind the puzzle.',
  'shopBgSoft': 'Glow',
  'shopBgSoftDesc': 'A soft wash behind the board.',
  'shopBgDusk': 'Stage',
  'shopBgDuskDesc': 'A deeper backdrop, still easy to read.',
  'shopSkinDefault': 'Clean cell',
  'shopSkinDefaultDesc': 'Simple highlight on the selected cell.',
  'shopSkinSoft': 'Soft cell',
  'shopSkinSoftDesc': 'A lighter wash on the selected row and box.',
  'shopSkinSharp': 'Sharp cell',
  'shopSkinSharpDesc': 'A stronger border on the selected cell.',
  'shopSkinGlow': 'Glow cell',
  'shopSkinGlowDesc': 'A bloom on the cell you are filling.',
  'shopRemoveAds': 'Remove ads',
  'shopRemoveAdsDesc': 'One-time. Hide the banner.',
  'adLabel': 'Ad',
  'adBannerSlot': 'AdMob banner',
  'adRemoveHint': 'Remove',
  'shopFeatPro': 'SudokuNote Pro',
  'shopFeatProDesc': 'Keep a longer list of finished puzzles.',
  'shopFeatDoubleCoins': 'Double coins',
  'shopFeatDoubleCoinsDesc': 'Twice the coins from solves and daily rewards.',
  'shopFeatSound': 'Tap sound',
  'shopFeatSoundDesc': 'A light click when you enter a number or note.',
  'shopFeatAwake': 'Keep screen on',
  'shopFeatAwakeDesc': 'The screen stays awake while you solve.',
  'shopFeatHint': 'Hints',
  'shopFeatHintDesc': 'Fill the selected empty cell. Three hints per puzzle.',
  'hint': 'Hint',

  'settings': 'Settings',
  'appearance': 'Appearance',
  'themeSystem': 'System',
  'themeLight': 'Light',
  'themeDark': 'Dark',
  'resetLook': 'Reset look to default',
  'about': 'About',
  'aboutBody':
      'SudokuNote is a Sudoku game with pencil notes. Pick a difficulty, fill 1–9 with no repeats in a row, column, or 3×3 box, undo a move, and resume a saved game. Progress stays on this device.',
  'privacyPolicy': 'Privacy policy',
  'privacyPolicyTitle': 'Privacy Policy — SudokuNote',
  'privacyPolicyBody':
      'SudokuNote stores games, coins, and shop unlocks on this device. We do not create an account.\n\n'
      'Google Play Billing handles coin packs, Remove ads, and SudokuNote Pro. A remote config file is fetched only to read a disable flag for billing popups. No puzzle progress is uploaded.\n\n'
      'Contact the developer through the Play Store listing.',
};
